* Emacs config
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src
Do not need to run 'doom sync' after modifying this file!
** Functions

*** Check if font is installed and change
#+begin_src emacs-lisp
(defun font-installed? (font-name)
  "Retorna t se a fonte font-name está instalada"
  (if (find-font (font-spec :name font-name))
      t nil))
#+end_src

** Basic
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets. It is optional.
#+begin_src emacs-lisp
(setq user-full-name "Paulo Suderio"
      user-mail-address "paulo.suderio@gmail.com")
#+end_src
This determines the style of line numbers in effect. If set to `nil', line numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative
      evil-respect-visual-line-mode t
      which-key-idle-delay 0.8
      which-key-max-description-length 55
      which-key-separator " → " )
#+end_src
** UI
*** Theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-vibrant)
(add-to-list 'default-frame-alist '(alpha-background . 85)) ; For all new frames henceforth
#+end_src
*** Bell
Disables anoying bell
#+begin_src emacs-lisp
(setq visible-bell nil)
(setq ring-bell-function 'ignore)
#+end_src
*** Dashboard
#+begin_src emacs-lisp
(setq fancy-splash-image (file-name-concat doom-user-dir "emacs-logo.png"))
#+end_src
*** Fonts
Doom exposes five (optional) variables for controlling fonts in Doom:
 - `doom-font' -- the primary font to use
 - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
 - `doom-big-font' -- used for `doom-big-font-mode'; use this for
   presentations or streaming.
 - `doom-symbol-font' -- for symbols
 - `doom-serif-font' -- for the `fixed-pitch-serif' face
See 'C-h v doom-font' for documentation and more examples of what they accept.
#+begin_src emacs-lisp
(if (font-installed? "FiraCode Nerd Font")
    (setq doom-font (font-spec :family "FiraCode Nerd Font" :size 12 :weight 'semi-light)))

(if (font-installed? "FiraCode Nerd Font Propo")
    (setq doom-variable-pitch-font (font-spec :family "FiraCode Nerd Font Propo" :size 13)))

(if (font-installed? "FiraCode Nerd Font Mono")
    (setq doom-big-font (font-spec :family "FiraCode Nerd Font Mono" :size 16 :weight 'bold)))
#+end_src
** Org
`org-directory'must be set before org loads!
#+begin_src emacs-lisp
(setq org-directory "~/org/")
(setq org-agenda-files '("inbox.org" "work.org"))

;; Default tags
(setq org-tag-alist '(
                      ;; locale
                      (:startgroup)
                      ("personal" . ?h)
                      ("work" . ?w)
                      (:endgroup)
                      (:newline)
                      ;; misc
                      ("writing")
                      ("review")
                      ("reading")))

;; Org-refile: where should org-refile look?
;;(setq org-refile-targets 'FIXME)

;; Org-roam variables
;;(setq org-roam-directory "~/Org/org-roam/")
;;(setq org-roam-index-file "~/Org/org-roam/index.org")
;;; Optional variables

;; Advanced: Custom link types
;; This example is for linking a person's 7-character ID to their page on the
;; free genealogy website Family Search.
(setq org-link-abbrev-alist
      '(("family_search" . "https://www.familysearch.org/tree/person/details/%s")))
#+end_src
*** UI Tweaks
#+begin_src emacs-lisp
(setq-default org-startup-indented t
              org-pretty-entities t
              org-use-sub-superscripts "{}"
              org-hide-emphasis-markers t
              org-startup-with-inline-images t
              org-image-actual-width '(300))
#+end_src
*** Org Level Headers
#+begin_src emacs-lisp :tangle yes
(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.5))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.4))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.3))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.2))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.1)))))
#+end_src
*** TODO Journal
*** TODO Capture
#+begin_src emacs-lisp
(after! org
(setq org-capture-templates
      '(("c" "Default Capture" entry (file "inbox.org")
         "* TODO %?\n%U\n%i")
        ;; Capture and keep an org-link to the thing we're currently working with
        ("r" "Capture with Reference" entry (file "inbox.org")
         "* TODO %?\n%U\n%i\n%a")
        ;; Define a section
        ("w" "Work")
        ("wm" "Work meeting" entry (file+headline "work.org" "Meetings")
         "** TODO %?\n%U\n%i\n%a")
        ("wt" "Work task" entry (file+headline "work.org" "Tasks")
         "** TODO %c\n%U\n[[http://itsmweb.bndes.net/servlet/ViewFormServlet?form=TMS%3ATask&server=itsm.bndes.net&eid=%c][remedy]]\n%?")
        ("wi" "Work incident" entry (file+headline "work.org" "Incidents")
         "** TODO %c\n%U\n[[http://itsmweb.bndes.net/servlet/ViewFormServlet?form=HPD%3AHelp+Desk&server=itsm.bndes.net&eid=%c][remedy]]\n%?")
        ("wa" "Work adhoc" entry (file+headline "work.org" "Ad hoc")
         "** TODO %?\n%U\n%i\n%a")
        ("wr" "Work report" entry (file+headline "work.org" "Reports")
         "** TODO %?\n%U\n%i\n%a"))))
#+end_src
*** TODO Workflow
#+begin_src emacs-lisp
(after! org
(setq org-log-done 'time
      org-todo-keywords '((sequence "TODO" "WAITING" "DOING" "|" "DONE(!)" "CANCELLED(!)"))
;; Refile configuration
      org-outline-path-complete-in-steps nil
      org-refile-use-outline-path 'file))
#+end_src
*** TODO Agenda
#+begin_src emacs-lisp
(setq org-agenda-custom-commands
      '(("n" "Agenda and All Todos"
         ((agenda)
          (todo)))
        ("w" "Work" agenda ""
         ((org-agenda-files '("work.org"))))))
#+end_src
*** TODO Export
#+begin_src emacs-lisp

;; Make org-open-at-point follow file links in the same window
;;(setf (cdr (assoc 'file org-link-frame-setup)) 'find-file)

;; Make exporting quotes better
(setq org-export-with-smart-quotes t
      org-export-with-drawers nil
      org-export-with-todo-keywords nil
      org-export-with-broken-links t
      org-export-with-toc nil
      org-export-date-timestamp-format "%d %B %Y")
;; Export ODT to MS-Word
(setq-default org-odt-preferred-output-format "docx")
;; Export ODT to PDF
;; (setq-default org-odt-preferred-output-format "pdf")
#+end_src
*** Org-tempo
Org-tempo is not a separate package but a module within org that can be enabled.  Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.  Other expansions available include:

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |
#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src
** Magit
Obs.: diff-refine-hunk may be slow
#+begin_src emacs-lisp
(after! magit
  (setq magit-revision-show-gravatars '("^Author:     " . "^Commit:     ")))
(after! magit
  (setq magit-diff-refine-hunk 'all))
#+end_src
** Languages
*** Julia
#+begin_src emacs-lisp
(setq lsp-julia-package-dir nil)
(after! lsp-julia
  (setq lsp-julia-default-environment "~/.julia/environments/v1.11"))
#+end_src
** TODO biblio config
 (setq org-cite-csl-styles-dir "~/Zotero/styles")
 (setq! citar-bibliography '("/path/to/references.bib"))
 (setq! citar-library-paths '("/path/to/library/files/")
       citar-notes-paths '("/path/to/your/notes/"))
** TODO see lsp-mode configuration

(https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/)
** TODO configurar latex
 (setq reftex-default-bibliography "/your/bib/file.bib")

https://github.com/james-stoup/emacs-org-mode-tutorial

** Remember
Whenever you reconfigure a package, make sure to wrap your config in an
 `after!' block, otherwise Doom's defaults may override your settings. E.g.

   (after! PACKAGE
     (setq x y))

 The exceptions to this rule:

   - Setting file/directory variables (like `org-directory')
   - Setting variables which explicitly tell you to set them before their
     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
   - Setting doom variables (which start with 'doom-' or '+').

 Here are some additional functions/macros that will help you configure Doom.

 - `load!' for loading external *.el files relative to this one
 - `use-package!' for configuring packages
 - `after!' for running code after a package has loaded
 - `add-load-path!' for adding directories to the `load-path', relative to
   this file. Emacs searches the `load-path' when you load packages with
   `require' or `use-package'.
 - `map!' for binding new keys

 To get information about any of these functions/macros, move the cursor over
 the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
 This will open documentation for it, including demos of how they are used.
 Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
 etc).

 You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
 they are implemented.
