- name: Install the bare minimum
  ansible.builtin.package:
    name:
      - openssh
      - base-devel
      - cmake
      - mpv
      - sxiv
      - jq
      - zip
      - unzip
      - git
      - less
      - curl
      - wget
      - ripgrep
      - shellcheck
      - file
      - neovim
      - python-pynvim
      - xclip
    state: latest
  become: true

- name: Install the cli tools
  ansible.builtin.package:
    name:
      - github-cli
      - aria2
      - aspell
      - bat
      - biber
      #- bandwhich
      #- bottom
      - ctop
      - git-delta
      - exa
      - fd
      - direnv
      - fzf
      - fzy
      - git-lfs
      # - glow
      - gnupg
      - gnuplot
      - htop
      # - httpie
      # - hub
      # - hyperfine
      # - languagetool
      # - lazydocker
      - lazygit
      - nnn
      - ncdu
      # - osmium-tool
      - pass
      - prettier
      - procs
      # - qemu
      # - ranger
      # - shfmt
      # - tealdeer
      - tree-sitter-cli
      # - tmux
      # - tmuxinator
      # - tokei
      # - weechat
      # - wezterm
      # - zoxide
      - zellij
    state: latest
  become: true

- name: Install the gui tools
  ansible.builtin.package:
    name:
      - zathura
      # zathura-djvu: DjVu support
      # zathura-pdf-poppler: PDF support using Poppler
      # zathura-pdf-mupdf: PDF support using MuPDF
      # zathura-ps: PostScript support
      # zathura-cb: Comic book support
      - xdotool
    state: latest
  become: true
- name: Install languages
  ansible.builtin.package:
    name:
      - luarocks
      - rubygems
      - npm
      - composer
      - jdk-openjdk
      - python-pipenv
      - julia
      - cpanminus
    state: latest
  become: true

- name: Install "neovim" node.js package globally.
  community.general.npm:
    name: neovim
    global: true
  become: true

- name: Install latest available version of neovim gem
  community.general.gem:
    name: neovim
    state: latest

- name: Install Neovim perl package
  community.general.cpanm:
    name: Neovim::Ext
    notest: true
