- name: Install the bare minimum
  ansible.builtin.package:
    name:
      - cmake
      - mpv
      - sxiv
      - jq
      - zip
      - unzip
      - git
      - less
      - curl
      - wget
      - ripgrep
      - shellcheck
      - file
      - neovim
      - xclip
      - aria2
      - aspell
      - bat
      - biber
      - git-delta
      - direnv
      - fzf
      - fzy
      - git-lfs
      - gnupg
      - gnuplot
      - htop
      - nnn
      - ncdu
      - pass
      - sshfs
      - tree-sitter-cli
      - viu
      - chafa
      - ueberzugpp
      - texlive
      - texlive-langenglish
      - texlive-langportuguese
      - python-pylatexenc
      - pandoc
      - lynis
      - clamav
    state: present
  become: true

- name: Install the bare minimum (package dependent)
  ansible.builtin.package:
    name:
      - openssh
      - base-devel
#      - openssh-client
#      - build-essential
      - python-pynvim
#      - python3-pynvim
#      - ruby-neovim
      - github-cli
#      - gh
      - ctop
#      # - ctop
      - exa
      - fd
#        # - exa
#        # - fd
      - lazygit
#      # - lazygit
      - prettier
      - procs
#        # - prettier
#        #- procs
      - zellij
#      # - zellij
    state: present
  become: true

- name: Install the gui tools
  ansible.builtin.package:
    name:
      - zathura
      - zathura-djvu
      - zathura-ps
      - zathura-cb
      - xdotool
    state: present
  become: true
- name: Install languages
  ansible.builtin.package:
    name:
      - luarocks
      - rubygems
      - npm
      - composer
      - jdk-openjdk
      - python-pipenv
      - julia
#      - default-jdk
#      - pipenv
#        #- julia
      - cpanminus
    state: present
  become: true

- name: Install "neovim" node.js package globally.
  community.general.npm:
    name: neovim
    global: true
  become: true

- name: Install present available version of neovim gem
  community.general.gem:
    name: neovim
    state: present

- name: Install Neovim perl package
  community.general.cpanm:
    name: Neovim::Ext
    notest: true
