- name: Install the bare minimum
  ansible.builtin.package:
    name:
      - cmake
      - mpv
      - sxiv
      - jq
      - zip
      - unzip
      - git
      - less
      - curl
      - wget
      - ripgrep
      - shellcheck
      - file
      - neovim
      - xclip
      - aria2
      - aspell
      - bat
      - biber
      - git-delta
      - direnv
      - fzf
      - fzy
      - git-lfs
      - gnupg
      - gnuplot
      - htop
      - nnn
      - ncdu
      - pass
      - sshfs
      - tree-sitter-cli
      - viu
      - chafa
      - ueberzugpp
      - texlive
      - texlive-langenglish
      - texlive-langportuguese
      - python-pylatexenc
      - pandoc
      - lynis
      - clamav
      - emacs-wayland
    state: present
  become: true

- name: Install the bare minimum (package dependent)
  ansible.builtin.package:
    name:
      - openssh
      - base-devel
      - python-pynvim
      - github-cli
      - ctop
      - exa
      - fd
      - lazygit
      - prettier
      - procs
      - zellij
    state: present
  become: true

- name: Install the gui tools
  ansible.builtin.package:
    name:
      - zathura
      - zathura-djvu
      - zathura-ps
      - zathura-cb
      - xdotool
    state: present
  become: true

- name: Install languages
  ansible.builtin.package:
    name:
      - luarocks
      - rubygems
      - npm
      - composer
      - jdk-openjdk
      - python-pipenv
      - julia
      - cpanminus
    state: present
  become: true

- name: Install other tools
  ansible.builtin.package:
    name:
      - lua51
      - rustup
      - kitty
      - ghostty
      - imagemagick
      - sbcl
      - gopls
      - python-isort
      - python-nose
      - python-nose2
      - python-pytest
      - python-setuptools
      - zig
      - kotlin
      - ktlint
      - markdownlint
      - bash-language-server
      - zshdb
      - shfmt
      - tidy
      - stylelint
      - zls
      - eza
      - just
      - starship
    state: present
  become: true
  tags: new

- name: Install "neovim" node.js package globally.
  community.general.npm:
    name: neovim
    global: true
  become: true

- name: Install present available version of neovim gem
  community.general.gem:
    name: neovim
    state: present

- name: Install Neovim perl package
  community.general.cpanm:
    name: Neovim::Ext
    notest: true

- name: Install "mermaid" node.js package globally.
  community.general.npm:
    name: "@mermaid-js/mermaid-cli"
    global: true
  become: true
  tags: new

- name: Install "js-beautify" node.js package globally.
  community.general.npm:
    name: "js-beautify"
    global: true
  become: true
  tags: new

- name: Install "ast-grep" Rust package
  community.general.cargo:
    name: ast-grep
  tags: new

# TODO 
  # go install github.com/fatih/gomodifytags@latest
  # go install github.com/cweill/gotests/gotests@latest
  # go install github.com/x-motemen/gore/cmd/gore@latest
  # rustup component add rust-analyzer
  # paru -S bashdb
