#!/bin/sh

exists() {
  command -v "$1" >/dev/null 2>&1
}
# Use neovim as vim
exists nvim && alias vim='nvim'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Always recover a session named $USER
alias restmux='[[ -z "$TMUX" ]] && exec tmux new-session -A -s $USER'

# Remember to run this now and then
alias scan='sudo freshclam && sudo clamscan -roi --exclude-dir="^/sys" --cross-fs=no'

# Common pacman use
alias fixpacman="sudo rm /var/lib/pacman/db.lck"
alias rmpkg="sudo pacman -Rdd"
alias gitpkg='pacman -Q | grep -i "\-git" | wc -l' # List amount of -git packages
# Cleanup orphaned packages
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
# Recent installed packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
# Sort installed packages according to size in MB
alias big="expac -H M '%m\t%n' | sort -h | nl"
alias pacdiff='sudo -H DIFFPROG=meld pacdiff'

# Get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
# This is too hard to remember
alias show-dependencies='pacman -Qe | cut -d" " -f 1 | while read in; do pactree -r "$in"; done'
! exists yay && exists paru && alias yay='paru'

if exists eza; then
# Replace ls with exa
  alias l='eza -Al --color=always --group-directories-first --icons'     # preferred listing
  alias la='eza -A --color=always --group-directories-first --icons'      # all files and dirs
  alias ll='eza -l --color=always --group-directories-first --icons'      # long format
  alias lt='eza -aT --color=always --group-directories-first --icons'     # tree listing
  alias l.='eza -ald --color=always --group-directories-first --icons .*' # show only dotfiles
else
  alias ll='ls -l'
  alias la='ls -A'
  alias lt='ls -aT'
  alias l.='ls -ald'
fi
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
  alias ip='ip -color'
fi

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

alias lcd=changeDirectory
changeDirectory() {
  cd "$1" || exit 1; l
}

exists bat && alias cat='bat --style header --style snip --style changes --style header'

alias meminfo='free -m -l -t'

alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

alias cpuinfo='lscpu'
alias hw='hwinfo --short'

alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'

alias diskspace="du -S | sort -n -r |more"

alias dockrrmi='docker images | grep '\''<none>'\'' | grep -P '\''[1234567890abcdef]{12}'\'' -o | xargs -L1 docker rmi'
alias dockrrm='docker ps -a | grep -v '\''CONTAINER\|_config\|_data\|_run'\'' | cut -c-12 | xargs docker rm'
alias dockerm='docker rm -v $(docker ps -a -q -f status=exited)'
alias dockermi='docker rmi $(docker images -f "dangling=true" -q)'
alias dockermv='docker volume rm $(docker volume ls -qf dangling=true)'

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias eclipse='eclipse --launcher.ini $HOME/.config/eclipse/eclipse.ini'

alias config='git --git-dir=$HOME/.local/dotfiles/ --work-tree=$HOME'
alias lazyconfig='lazygit --git-dir=$HOME/.local/dotfiles/ --work-tree=$HOME'

alias show-dependencies='pacman -Qe | cut -d" " -f 1 | while read in; do pactree -r "$in"; done'

# Get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"

alias tb='nc termbin.com 9999'
