#!/bin/bash
# manage dotfiles with git, see https://www.atlassian.com/git/tutorials/dotfiles
alias config='git --git-dir="$HOME"/.local/dotfiles/ --work-tree="$HOME"'

# Config in new machine
# git clone --bare git@github.com:user/dotfiles $HOME/.local/dotfiles
# config config --local status.showUntrackedFiles no
# config checkout

configsync() {
  git-sync -g "$HOME/.local/dotfiles" -w "$HOME" -ns sync
  git-sync -C "$HOME/org" -ns sync
}

configstatus() {
  git-sync -g "$HOME/.local/dotfiles" -w "$HOME" -s check
  git-sync -C "$HOME/org" -s check
}
