#+title: Suderio's GNU Emacs Config
#+AUTHOR: Paulo Suderio
#+DESCRIPTION: Suderio's personal Emacs config.
#+STARTUP: showeverything
#+OPTIONS: toc:2

* TABLE OF CONTENTS :toc:
- [[#important-things-to-do-first][IMPORTANT THINGS TO DO FIRST]]
  - [[#what-should-be-installed-in-your-os][What should be installed in your OS]]
  - [[#non-versioned-local-files][Non-versioned, local files]]
  - [[#adding-the-scripts-directory-to-path][Adding the scripts directory to path]]
  - [[#loading-elpaca][Loading Elpaca]]
  - [[#no-littering][No littering]]
  - [[#backup][Backup]]
  - [[#loading-the-scripts][Loading the scripts]]

* IMPORTANT THINGS TO DO FIRST
These are the bare minimum.

This configuration was heavily influenced by:
- https://github.com/iocanel/emacs.d
- https://gitlab.com/dwt1/dashboard-set-file-icons
- https://codeberg.org/ashton314/emacs-bedrock/src/branch/main/init.el

** What should be installed in your OS
We must install a bunch of os packages in order to everything work:
#+begin_src emacs-lisp

(when (< emacs-major-version 29)
  (error (format "Evilmacs only works with Emacs 29 and newer; you have version ~a" emacs-major-version)))

(defun em/check-os-deps (dep)
  "Checks and reports missing dependencies"
  (unless (executable-find dep) (message "%s is not installed, some packages may not work" dep))
)
(em/check-os-deps "cmake")
(em/check-os-deps "mpv")
(em/check-os-deps "sxiv")
(em/check-os-deps "unzip")
(em/check-os-deps "pdflatex")
(em/check-os-deps "jq")
#+end_src
** Non-versioned, local files
Everything temporary should go in the .local directory.
#+begin_src emacs-lisp
;; (defvar em/local-dir (expand-file-name ".local/" user-emacs-directory) "Local state directory")
(setq no-littering-etc-directory (expand-file-name "config/" user-emacs-directory)
      no-littering-var-directory (expand-file-name "data/" user-emacs-directory))
#+end_src
** Adding the scripts directory to path
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.config/emacs/scripts/")
#+end_src
** Loading Elpaca
#+begin_src emacs-lisp
(org-babel-tangle-file "~/.config/emacs/scripts/elpaca.org")

(load "elpaca")  ;; Elpaca Configurations
#+end_src

** No littering
#+begin_src emacs-lisp
(use-package no-littering
   :ensure t)
;; Emacs will save customizations into your init.el file by default. Instead, save in the "etc" directory:
(setq custom-file (expand-file-name "custom.el" no-littering-etc-directory))
#+end_src
** Backup 
By default, Emacs creates automatic backups of files in their original directories, such "file.el" and the backup "file.el~".  This leads to a lot of clutter, so let's tell Emacs to put all backups that it creates in the =TRASH= directory.
#+begin_src emacs-lisp
(setq backup-directory-alist '((".*" . "~/.local/share/Trash/files")))

#+end_src
** Loading the scripts
#+begin_src emacs-lisp
(org-babel-tangle-file "~/.config/emacs/scripts/window.org")
(org-babel-tangle-file "~/.config/emacs/scripts/gui.org")
(org-babel-tangle-file "~/.config/emacs/scripts/evil.org")
(org-babel-tangle-file "~/.config/emacs/scripts/other.org")

(load "window")  ;; Windows' Configurations
(load "gui")  ;; GUI Configurations
(load "evil")  ;; Evil Configurations
(load "other")  ;; Evil Configurations
#+end_src
