version: '3.8'

services:
  centos-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    image: centos-dev:latest
    container_name: centos-dev
    volumes:
      - $HOME:$HOME
    working_dir: $HOME
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true

