#!/bin/bash

set -e

function install_ansible {
  DIST=$(cat /etc/*release | grep -e "^ID=" | cut -d= -f2)
  case "$DIST" in
  arch)
    sudo pacman -S ansible
    ;;

  garuda)
    sudo pacman -S ansible
    ;;

  ubuntu)
    sudo apt install -y ansible
    ;;

  debian)
    sudo apt-get install -y ansible
    ;;
  esac
}
# install ansible
command -v ansible &>/dev/null || install_ansible

# Run Ansible

ansible-playbook -i ./hosts.yml ./linux.yml --ask-become-pass
