live_config_reload = true

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font]
size = 11.0

[font.bold]
family = "Fira Code Bold Nerd Font Complete"

[font.bold_italic]
family = "FiraCode Nerd Font Mono Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono Medium Italic"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login"]
program = "/usr/bin/bash"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.7
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30
