#save_to_clipboard = true
#theme = "Catppuccin"
#"window.dynamic_title" = true

[colors]
draw_bold_text_with_bright_colors = true
#semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#ffffff"
yellow = "#e7c547"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.dim]
black = "#000000"
blue = "#506d8f"
cyan = "#497e7a"
green = "#7a8530"
magenta = "#80638e"
red = "#8c3336"
white = "#9a9a9a"
yellow = "#97822e"

[colors.normal]
black = "#000000"
blue = "#7aa6da"
cyan = "#70c0ba"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e6c547"

[colors.primary]
background = "#000000"
bright_foreground = "#ffffff"
dim_foreground = "#9a9a9a"
foreground = "#eaeaea"

[colors.selection]
background = "#404040"
text = "#eaeaea"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Fira Code Bold Nerd Font Complete"

[font.bold_italic]
family = "FiraCode Nerd Font Mono Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono Medium Italic"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/usr/bin/bash"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.7
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[general]
live_config_reload = true

[terminal]
