- name: Install the bare minimum
  ansible.builtin.package:
    name:
      - cmake
      - mpv
      - sxiv
      - jq
      - wget
      - ripgrep
      - shellcheck
      - neovim
      - xclip
      - aria2
      - aspell
      - bat
      - biber
      - git-delta
      - direnv
      - fzf
      - fzy
      - git-lfs
      - gnuplot
      - htop
      - nnn
      - ncdu
      - pass
      - sshfs
      - tree-sitter-cli
      - viu
      - chafa
      - ueberzugpp
      - texlive
      - texlive-langenglish
      - texlive-langportuguese
      - python-pylatexenc
      - pandoc
      - lynis
      - clamav
      - python-pynvim
      - github-cli
      - ctop
      - exa
      - fd
      - lazygit
      - prettier
      - procs
      - zellij
      - zathura
      - zathura-djvu
      - zathura-ps
      - zathura-cb
      - xdotool
      - luarocks
      - npm
      - composer
      - jdk-openjdk
      - python-pipenv
      - julia
      - emacs
      - git
      - man-db
      - mandrel24-bin
      - nano
      - nodejs
      - nushell
      - quarkuscli-bin
      - ranger
      - rubygems
      - rustup
      - shfmt
      - stylua
      - tealdeer
      - thunderbird
      - xorg-bdftopcf
      - xorg-iceauth
      - xorg-mkfontscale
      - xorg-sessreg
      - xorg-setxkbmap
      - xorg-smproxy
      - xorg-x11perf
      - xorg-xauth
      - xorg-xbacklight
      - xorg-xclock
      - xorg-xcmsdb
      - xorg-xcursorgen
      - xorg-xdpyinfo
      - xorg-xdriinfo
      - xorg-xev
      - xorg-xgamma
      - xorg-xhost
      - xorg-xinput
      - xorg-xkbcomp
      - xorg-xkbevd
      - xorg-xkbprint
      - xorg-xkbutils
      - xorg-xkill
      - xorg-xlsatoms
      - xorg-xlsclients
      - xorg-xmodmap
      - xorg-xpr
      - xorg-xrandr
      - xorg-xrdb
      - xorg-xrefresh
      - xorg-xset
      - xorg-xsetroot
      - xorg-xvinfo
      - xorg-xwd
      - xorg-xwininfo
      - xorg-xwud
      - yay
      - yay-debug
#      - cpanminus wl-clipboard starship kitty lua51 imagemagick ripgrep-all zig just ghostty clamav libpwquality python-pylatexenc texlive-langenglish texlive-langportuguese viu chafa ueberzugpp
    state: absent
  become: true
