[bootstrap.packages]
"pacman:base-devel" = "latest"
"pacman:curl" = "latest"
"pacman:cabal" = "latest"
"pacman:clang" = "22.1.3"
"pacman:clojure" = "latest"
"pacman:go" = "latest"
"pacman:java" = "latest"
"pacman:julia" = "latest"
"pacman:kotlin" = "latest"
"pacman:lua" = "5.1.5"
"pacman:nodejs" = "latest"
"pacman:openssl" = "latest"
"pacman:perl" = "latest"
"pacman:php" = "8.5.0"
"pacman:python" = "latest"
"pacman:ruby" = "latest"
"pacman:rust" = "latest"
"pacman:zig" = "latest"

[tools]
# basic tools
#ast-grep = "latest"
#bat = "latest"
#bat-extras = "latest"
#delta = "latest"
#eza = "latest"
#fd = "latest"
#fzf = "latest"
#ripgrep = "latest"
#ripgrep-all = "latest"
#starship = "latest"
#zellij = "latest"
