[settings]
experimental = true
dotfiles.root = "~/.local/.dotfiles"
dotfiles.default_mode = "symlink"

[env]
default_version="system"

[settings.cargo]
binstall = true

[settings.erlang]
compile = false

[settings.node]
compile = false
gpg_verify = true

[settings.python]
compile = false

[dotfiles]
"~/.bashrc.d" = { mode = "symlink-each" }
"~/.config" = { mode = "symlink-each" }
"~/.local" = { mode = "symlink-each" }
"~/.m2" = { mode = "symlink-each" }
"~/.ssh" = { mode = "symlink-each" }
"~/.bash_logout" = {}
"~/.bash_profile" = {}
"~/.bashrc" = {}
"~/.editorconfig" = {}
"~/.gitconfig" = {}
"~/.gitignore" = {}
"~/.inputrc" = {}
"~/.profile" = {}
"~/.Xresources" = {}

[plugins]
emacs = "https://github.com/suderio/misemacs"

[tools]
emacs = "latest"
neovim = "latest"

[tasks.neovim]
run = '''
    echo "Installing pynvim package"
    uv venv --clear "$XDG_DATA_HOME/nvim/venv"
    uv pip install pynvim -p "$XDG_DATA_HOME/nvim/venv"

    echo "Installing npm neovim package"
    npm install --global neovim

    echo "Installing ruby neovim gem"
    gem install neovim

    echo "Installing cpan neovim package"
    cpanm -n Neovim::Ext
'''


## devtools
#coreutils = "latest"
#just = "latest"
#github-cli = "latest"
#jj = "latest"
#jq = "latest"
#leiningen = "latest"
#lua-language-server = "latest"
#ninja = "latest"
#rust-analyzer = "latest"
#stylua = "latest"
#tinytex = "latest"
#yamlfmt = "latest"
#yamllint = "latest"
#yj = "latest"
#yq = "latest"
### go devtools
#"go:github.com/go-delve/delve/cmd/dlv" = "latest"
#
### python devtools
#"pipx:isort" = "latest"
#"pipx:pipenv" = "latest"
#"pipx:nose" = "latest"
#"pipx:nose2" = "latest"
#"pipx:pytest" = "latest"
#"pipx:pyflakes" = "latest"
#"pipx:citation-langserver" = "latest"
#"pipx:pyright" = "latest"
#"pipx:sqlfluff" = "latest"
#
### npm devtools
#"npm:vscode-json-languageserver" = "latest"
#"npm:typescript" = "latest"
#"npm:typescript-language-server" = "latest"
#"npm:bash-language-server" = "latest"
#"npm:dockerfile-language-server-nodejs" = "latest"
#"npm:yaml-language-server" = "latest"
#
## neovim dependencies
#prettier = "latest"
#
## cargo devtools
#"cargo:cargo-upgrade-command" = "latest"
#"cargo:https://github.com/latex-lsp/texlab" = "tag:v5.22.1"
#
## other
#bitwarden = "latest"
#ctop = "latest"
#dust = "latest"
#ffmpeg = "latest"
#pandoc = "latest"
#typst = "latest"
#"cargo:procs" = "latest"
#imagemagick = "latest"
#grpcurl = "latest"
#websocat = "latest"
#gitleaks = "latest"
#"go:github.com/pranshuparmar/witr/cmd/witr" = "latest"
#tinymist = "latest"
#babashka = "latest"
#youtube-dl = "latest"
#jwt = "latest"
#typstyle = "latest"
#"pipx:pylatexenc" = "latest"
#maven = "latest"
#lazyssh = "latest"
##rust = "latest"
#usql = "latest"
#btop = "latest"
#nfpm = "latest"
#
#[env]
#LOCAL_DIR = '{{env.HOME}}/.local'
#BIN_DIR = '{{env.LOCAL_DIR}}/bin'
#CONFIG_DIR = '{{env.HOME}}/.config'
#TMP_DIR = "{{env.HOME}}/tmp"
#
#[tasks.default]
#quiet = true
#dir = '{{env.TMP_DIR}}'
#run = [
#  'echo $LOCAL_DIR is the local directory',
#  'echo $BIN_DIR is the bin directory',
#  'echo $CONFIG_DIR is the config directory',
#  'echo $TMP_DIR is the tmp directory',
#]
#[tasks.clean]
#description = 'Deletes tmp dir'
#run = ['rm -rf "$TMP_DIR"/*', 'rm -rf "$TMP_DIR"/.[!.]*']
#
#
#[tasks.julia]
#run = 'julia -- "$CONFIG_DIR/julia/emacs.jl"'
#
#[tasks.php]
#depends = ['clean']
#dir = '{{env.TMP_DIR}}'
#run = '''
#    curl -fsSLo phpactor.phar --output-dir "$BIN_DIR" https://github.com/phpactor/phpactor/releases/latest/download/phpactor.phar
#    chmod u+x "$BIN_DIR/phpactor.phar"
#'''
#
#[tasks.ruby]
#run = 'gem install ruby-lsp'
#




#[tasks.java]
#depends = ['clean']
#dir = '{{env.TMP_DIR}}'
#run = '''
#    curl -fsSLo jdtls.tar.gz https://download.eclipse.org/jdtls/milestones/1.46.1/jdt-language-server-1.46.1-202504011455.tar.gz
#    mkdir -p "$LOCAL_DIR/etc/eclipse.jdt.ls"
#    tar -xvf jdtls.tar.gz -C "$LOCAL_DIR/etc/eclipse.jdt.ls/"
#'''
#
## Devido a um bug no gradle é preciso alterar a versão do java manualmente:
##  mise use java@temurin-11
##  ao final da execução voltar para a versão anterior:
##  mise use java@25
#[tasks.kotlin]
#depends = ['clean']
#dir = '{{env.TMP_DIR}}'
#tools.java = "temurin-11"
#run = '''
#  git clone https://github.com/fwcd/kotlin-language-server.git
#  cd kotlin-language-server
#  ./gradlew :server:installDist
#  cp server/build/install/server/bin/kotlin-language-server "$BIN_DIR"
#'''
#
#[tasks.perl]
#run = '''
#    cpanm local::lib
#    perl -I ~/perl5/lib/perl5 -Mlocal::lib
#    cpanm --notest --local-lib="$HOME/perl5" Perl::LanguageServer
#'''
#[tasks.update]
#run = '''
#    git --git-dir="$LOCAL_DIR/dotfiles/" --work-tree=$HOME pull
#    mise self-update
#    mise upgrade
#    cargo upgrade
#    uv tool upgrade --all
#    npm update --global
#    doom upgrade
#    echo "cljfmt, tidy, paru cannot be automatically updated"
#'''
#[tasks.ansi]
#run = ['curl -OL git.io/ansi', 'chmod 755 ansi', 'mv ansi "$LOCAL_DIR/bin/"']
#
## TODO
##NPM_PACKAGES := "markdownlint @mermaid-js/mermaid-cli"
## https://github.com/fwcd/kotlin-language-server
## ver .config/emacs/.local/etc/lsp/kotlin-language-server*
#
## json, python, just treesitter
## ver .config/emacs/.local/etc/tree-sitter/libtree-sitter-just.so
#
#
## see https://langserver.org/
## see https://microsoft.github.io/language-server-protocol/implementors/servers/
