[settings]
experimental = true
dotfiles.root = "~/.local/.dotfiles"
dotfiles.default_mode = "symlink"

[env]
default_version = "system"

[settings.cargo]
binstall = true

[settings.erlang]
compile = false

[settings.node]
compile = false
gpg_verify = true

[settings.python]
compile = false

[dotfiles]
"~/.bashrc.d" = { mode = "symlink-each" }
"~/.config" = { mode = "symlink-each" }
"~/.local" = { mode = "symlink-each" }
"~/.m2" = { mode = "symlink-each" }
"~/.ssh" = { mode = "symlink-each" }
"~/.bash_logout" = {}
"~/.bash_profile" = {}
"~/.bashrc" = {}
"~/.editorconfig" = {}
"~/.gitconfig" = {}
"~/.gitignore" = {}
"~/.inputrc" = {}
"~/.profile" = {}
"~/.Xresources" = {}

[plugins]
emacs = "https://github.com/suderio/misemacs"

[tools]
emacs = "latest"
neovim = "latest"

[tasks.neovim]
run = '''
    echo "Installing pynvim package"
    uv venv --clear "$XDG_DATA_HOME/nvim/venv"
    uv pip install pynvim -p "$XDG_DATA_HOME/nvim/venv"

    echo "Installing npm neovim package"
    npm install --global neovim

    echo "Installing ruby neovim gem"
    gem install neovim

    echo "Installing cpan neovim package"
    cpanm -n Neovim::Ext
'''
