[bootstrap.packages]
"pacman:base-devel" = "latest"
"pacman:curl" = "latest"
"pacman:cabal-install" = "latest"
"pacman:clang" = "latest"
"pacman:clojure" = "latest"
"pacman:leiningen" = "latest"
"pacman:go" = "latest"
"pacman:jdk-openjdk" = "latest"
"pacman:julia" = "latest"
"pacman:kotlin" = "latest"
"pacman:lua51" = "latest"
"pacman:nodejs" = "latest"
"pacman:openssl" = "latest"
"pacman:perl" = "latest"
"pacman:php" = "latest"
"pacman:python" = "latest"
"pacman:zig" = "latest"
"pacman:ruby" = "latest"
"pacman:ruby-stdlib" = "latest"
"pacman:rust" = "latest"
"pacman:sbcl" = "latest"

# basic tools
"pacman:ast-grep" = "latest"
"pacman:bat" = "latest"
"pacman:bat-extras" = "latest"
"pacman:git-delta" = "latest"
"pacman:eza" = "latest"
"pacman:fd" = "latest"
"pacman:fzf" = "latest"
"pacman:ripgrep" = "latest"
"pacman:ripgrep-all" = "latest"
"pacman:starship" = "latest"
"pacman:zellij" = "latest"


# emacs deps
"pacman:python-black" = "latest"
"pacman:cmake" = "latest"

"pacman:tree-sitter" = "latest"
"pacman:pandoc" = "latest"
"pacman:shellcheck" = "latest"
"pacman:shfmt" = "latest"
"pacman:libgccjit" = "latest"


#"cargo:emacs-lsp-booster" = "latest"
#clang-format = "22.1.3"
#"go:golang.org/x/tools/gopls" = "latest"
#"go:github.com/chrishrb/go-grip" = "latest"
#"go:github.com/cweill/gotests/gotests" = "latest"
#"go:github.com/fatih/gomodifytags" = "latest"
#"go:github.com/jessfraz/dockfmt" = "latest"
#"go:github.com/x-motemen/gore/cmd/gore" = "latest"
#ktlint = "latest"
#"npm:js-beautify" = "latest"
#"npm:stylelint" = "latest"
#uv = "latest"
#zls = "latest"
#
## neovim deps
#lazygit = "latest"
#"npm:@mermaid-js/mermaid-cli" = "latest"
#
## shell
#babashka = "latest"
[tools]
