[bootstrap.packages]
"apt:curl" = "latest"

[tools]
# languages
cabal = "latest"
clang = "22.1.3"
clojure = "latest"
go = "latest"
java = "latest"
julia = "latest"
kotlin = "latest"
lua = "5.1.5"
nodejs = "latest"
#perl = "latest"
#php = "8.5.0"
python = "latest"
ruby = "latest"
rust = "latest"
zig = "latest"

# basic tools
ast-grep = "latest"
bat = "latest"
bat-extras = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
starship = "latest"
emacs = "latest"
